# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: null
    param_fetcher_listener:  true
    routing_loader:
      default_format: json
      include_format: false
    body_listener: true
    access_denied_listener:
      json: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ json ] }
    view:
      view_response_listener: 'force'
      formats:
        json: true
