nelmio_api_doc:
    documentation:
        info:
            title: Simple API
            description: This is an awesome Simple API app!
            version: 1.0.0
        components:
            securitySchemes:
                api_key:
                    type: apiKey
                    name: Auth-Token
                    in: header
                    description: "The key is: %env(resolve:AUTH_TOKEN)%"

    areas: # to filter documented areas
        path_patterns:
            - ^/(?!doc(.json)?$)(?!_error.*$) # Accepts routes under /api except /api/doc
